name: seismic_analytics
version: "1.0.0"
config-version: 2

profile: seismic_analytics

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages", "logs"]

models:
  seismic_analytics:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: table
